import { Language } from '../shared/types';

export type TranslationKey =
  | 'liveTabs' | 'stash' | 'stashLibrary' | 'dropToStash' | 'findTabOrProject' | 'tabActions'
  | 'groupTabs' | 'cleanUp' | 'stashWindow' | 'keepPinnedActive' | 'stashAllTabs' | 'includePinnedActive'
  | 'quietlySynced' | 'deepScanOn' | 'adaptiveContext' | 'tabWorkspace' | 'openSettings'
  | 'zenTabSections' | 'browserWindows' | 'window' | 'privateWindow' | 'scanningAllPageContext' | 'enrichingUncertainTabs' | 'findingLowValueTabs' | 'workingQuietly'
  | 'stashingGroup' | 'stashingTab' | 'stashingWindow' | 'stashingAllTabs' | 'stashingSelectedTabs' | 'stashingUngrouped'
  | 'projectContextEnriched' | 'projectContextMetadata' | 'actionFailed' | 'couldNotAnalyzeWindow' | 'couldNotScanWindow'
  | 'tabsStashed' | 'tabsClosed' | 'tabsClosedWithSkipped' | 'tabsCount' | 'groupsCreated' | 'couldNotStashTabs' | 'couldNotCloseTabs' | 'lastActionRestored' | 'nothingToUndo' | 'tabsRestoredWithSkipped' | 'restoringTabs'
  | 'deepScanReady' | 'adaptiveMetadataEnabled' | 'permissionDenied' | 'openingZenTab' | 'connectingToTabs'
  | 'noMatchingTabs' | 'clearWindow' | 'tryShorterTitle' | 'openTabToAppear' | 'selected' | 'selectionMode'
  | 'exitSelection' | 'moveTabToStart' | 'untitledGroup' | 'ungrouped' | 'untitledTab' | 'selectTab' | 'deselectTab' | 'selectGroup'
  | 'clickToSelect' | 'actionsFor' | 'playingAudio' | 'discarded' | 'pinned' | 'mute' | 'unmute' | 'pin' | 'unpin' | 'close' | 'done' | 'undo' | 'dismiss'
  | 'projectMap' | 'suggestedGroups' | 'checkTabsEvidence' | 'suggestionsToReview' | 'tabsNeedMoreContext' | 'noValidGroups' | 'invalidGroupName'
  | 'reviewBeforeApplying' | 'keepAsIs' | 'createGroups' | 'applying' | 'lowValueScan' | 'possibleCleanups'
  | 'nothingCloses' | 'protectedPages' | 'conservative' | 'noProtectedPages' | 'leaveEverything' | 'noSafeCleanup'
  | 'contextIntentional' | 'recoverableContext' | 'stashLibraryDescription' | 'stashSearch' | 'noMatchingStashes' | 'saved' | 'nextFocus' | 'restore' | 'restoreTab' | 'restoreGroup' | 'delete' | 'renameStash' | 'expandStash' | 'collapseStash' | 'stashRenamed' | 'invalidStashName'
  | 'tabsOpening' | 'stashDeleted' | 'couldNotRestoreStash' | 'couldNotDeleteStash' | 'stashEmptyDescription' | 'pageNoLongerAvailable' | 'keptAside' | 'couldNotSaveGroqKey' | 'groqKeySaved' | 'controlRoom' | 'settings'
  | 'settingsDescription' | 'language' | 'languageDescription' | 'theme' | 'themeDescription' | 'systemTheme' | 'lightTheme'
  | 'darkTheme' | 'duplicateGuard' | 'catchRepeated' | 'matchScope' | 'allNormalWindows' | 'currentWindowOnly'
  | 'deepScanAll' | 'deepScanDescription' | 'deepScanPrivacy' | 'aiProvider' | 'localAutomatic' | 'groqByok' | 'groqApiKey'
  | 'savedLocally' | 'clearApiKey' | 'groqPrivacy' | 'groqPermissionDenied' | 'couldNotSaveSettings' | 'protectedDomains' | 'protectedDomainsDescription' | 'protectedDomainsPlaceholder'
  | 'settingsFootnote' | 'strongMatch' | 'possibleMatch' | 'needsReview' | 'severalSignals' | 'someSignals' | 'limitedContext' | 'moveTo' | 'unclassified' | 'renameGroup' | 'changeGroupColor' | 'ungroup' | 'groupUpdated' | 'clearProjectMemory' | 'clearProjectMemoryDescription' | 'clearProjectMemoryConfirm' | 'projectMemoryCleared' | 'groupColorGrey' | 'groupColorBlue' | 'groupColorCyan' | 'groupColorGreen' | 'groupColorYellow' | 'groupColorOrange' | 'groupColorRed' | 'groupColorPink' | 'groupColorPurple';

type TranslationValues = Record<string, string | number>;
export type Translator = (key: TranslationKey, values?: TranslationValues) => string;

const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    liveTabs: 'Live tabs', stash: 'Stash', stashLibrary: 'Stash library', dropToStash: 'Drop to stash', findTabOrProject: 'Find a tab or project', tabActions: 'Tab actions',
    groupTabs: 'Group tabs', cleanUp: 'Clean up', stashWindow: 'Stash window', keepPinnedActive: 'Keep pinned and active tabs', stashAllTabs: 'Stash all tabs', includePinnedActive: 'Include pinned and active tabs',
    quietlySynced: 'Quietly synced', deepScanOn: 'Deep scan on', adaptiveContext: 'Adaptive context', tabWorkspace: 'Tab workspace', openSettings: 'Open settings', zenTabSections: 'Zen Tab sections', browserWindows: 'Browser windows',
    window: 'Window {index}', privateWindow: 'Private window', scanningAllPageContext: 'Scanning all page context', enrichingUncertainTabs: 'Enriching uncertain tabs', findingLowValueTabs: 'Finding low-value tabs', workingQuietly: 'working quietly',
    stashingGroup: 'Stashing group', stashingTab: 'Stashing tab', stashingWindow: 'Stashing window', stashingAllTabs: 'Stashing all tabs', stashingSelectedTabs: 'Stashing selected tabs', stashingUngrouped: 'Stashing ungrouped tabs',
    projectContextEnriched: 'Project context enriched with page summaries.', projectContextMetadata: 'Project context built from tab metadata.', actionFailed: 'Action failed.', couldNotAnalyzeWindow: 'Could not analyze this window.', couldNotScanWindow: 'Could not scan this window.',
    tabsStashed: '{count} tabs stashed.', tabsClosed: '{count} tabs closed.', tabsClosedWithSkipped: '{closed} tabs closed; {skipped} skipped because their state changed.', tabsCount: '{count} tabs', groupsCreated: '{count} project groups created.', couldNotStashTabs: 'Could not stash those tabs.', couldNotCloseTabs: 'Could not close selected tabs.', lastActionRestored: 'Last action restored.', nothingToUndo: 'Nothing to undo.', tabsRestoredWithSkipped: '{created} tabs restored; {failed} could not be restored.', restoringTabs: 'Restoring tabs',
    deepScanReady: 'Deep scan all is ready.', adaptiveMetadataEnabled: 'Adaptive metadata analysis remains enabled.', permissionDenied: 'Chrome did not grant page-summary access.', openingZenTab: 'Opening Zen Tab', connectingToTabs: 'Connecting to Chrome tabs…',
    noMatchingTabs: 'No matching tabs', clearWindow: 'A clear window, for once.', tryShorterTitle: 'Try a shorter title or domain.', openTabToAppear: 'Open a tab and it will appear here instantly.', selected: 'selected', selectionMode: 'Selection mode · click rows to toggle', exitSelection: 'Exit selection mode', moveTabToStart: 'Move tab to start', untitledGroup: 'Untitled group', ungrouped: 'Ungrouped', untitledTab: 'Untitled tab', selectTab: 'Select {title}', deselectTab: 'Deselect {title}', selectGroup: 'Select group {name}', clickToSelect: 'Click to select or deselect', actionsFor: 'Actions for {title}', playingAudio: 'Playing audio', discarded: 'Discarded', pinned: 'Pinned', mute: 'Mute', unmute: 'Unmute', pin: 'Pin', unpin: 'Unpin', close: 'Close', done: 'Done', undo: 'Undo', dismiss: 'Dismiss',
    projectMap: 'PROJECT MAP', suggestedGroups: '{count} suggested groups', checkTabsEvidence: 'Check the tabs and evidence before creating browser groups. Uncertain tabs stay out.', suggestionsToReview: 'Suggestions to review', tabsNeedMoreContext: '{count} tabs need more context', noValidGroups: 'Select at least one group with two or more tabs.', invalidGroupName: 'Project names must be between 1 and 42 characters.', reviewBeforeApplying: 'Review before applying', keepAsIs: 'Keep as-is', createGroups: 'Create {count} groups', applying: 'Applying…', lowValueScan: 'LOW-VALUE SCAN', possibleCleanups: '{count} possible cleanups', nothingCloses: 'Nothing closes until you choose it. Protected pages are shown but cannot be selected.', protectedPages: 'Conservative by design', conservative: 'no active, pinned, local, or protected pages included', noProtectedPages: 'No protected pages included', leaveEverything: 'Leave everything', noSafeCleanup: 'No safe cleanup candidates.', contextIntentional: 'Your open context looks intentional.',
    recoverableContext: 'RECOVERABLE CONTEXT', stashLibraryDescription: 'Sessions live locally until you decide they should disappear.', stashSearch: 'Search saved sessions', noMatchingStashes: 'No matching sessions', saved: 'saved', nextFocus: 'Your next focus starts here.', restore: 'Restore', restoreTab: 'Restore tab', restoreGroup: 'Restore group', delete: 'Delete', renameStash: 'Rename stash', expandStash: 'Expand stash', collapseStash: 'Collapse stash', stashRenamed: 'Stash renamed.', invalidStashName: 'Use a stash name between 1 and 80 characters.', tabsOpening: '{count} tabs are opening in a new window.', stashDeleted: 'Stash deleted.', couldNotRestoreStash: 'Could not restore stash.', couldNotDeleteStash: 'Could not delete stash.', stashEmptyDescription: 'Stash a window or selected tabs to keep them for later.', pageNoLongerAvailable: 'Page no longer available', keptAside: '{count} kept aside. Their project signal is too weak or conflicted to make a safe call.', couldNotSaveGroqKey: 'Could not save the Groq key.', groqKeySaved: 'Groq key saved locally.',
    controlRoom: 'CONTROL ROOM', settings: 'Settings', settingsDescription: 'Small controls that keep automation inside your comfort zone.', language: 'Language', languageDescription: 'Choose the language for Zen Tab.', theme: 'Theme', themeDescription: 'Follow Chrome or choose a fixed appearance.', systemTheme: 'System (Chrome)', lightTheme: 'Light', darkTheme: 'Dark', duplicateGuard: 'Duplicate guard', catchRepeated: 'Catch repeated pages as they appear.', matchScope: 'Match scope', allNormalWindows: 'All normal windows', currentWindowOnly: 'Current window only', deepScanAll: 'Deep scan all tabs', deepScanDescription: 'Read up to 300 page summaries during Group tabs.', deepScanPrivacy: 'Off by default. Adaptive summaries use up to 32 uncertain tabs when access is available.', aiProvider: 'AI provider', localAutomatic: 'Local / automatic', groqByok: 'Groq (BYOK)', groqApiKey: 'Groq API key', savedLocally: 'Saved locally · enter to replace', clearApiKey: 'Clear API key', groqPrivacy: 'Stored separately from UI snapshots. Metadata and requested summaries are sent only when you choose Groq.', groqPermissionDenied: 'Groq network access was not granted; Local mode remains enabled.', couldNotSaveSettings: 'Could not save that setting.', protectedDomains: 'Protected domains', protectedDomainsDescription: 'Never suggest cleanup for these hosts.', protectedDomainsPlaceholder: 'figma.com, docs.google.com', settingsFootnote: 'Zen Tab never promises exact per-tab memory. It uses discard state and safe heuristics instead.', strongMatch: 'Strong match', possibleMatch: 'Possible match', needsReview: 'Needs review', severalSignals: 'Several signals point to the same project.', someSignals: 'Some signals overlap. Review the evidence before grouping.', limitedContext: 'Context is limited or conflicting.', moveTo: 'Move to', unclassified: 'Unclassified', renameGroup: 'Rename group', changeGroupColor: 'Change group color', ungroup: 'Ungroup', groupUpdated: 'Group updated.', clearProjectMemory: 'Clear learned grouping preferences', clearProjectMemoryDescription: 'Only explicit project choices are stored locally to improve future suggestions.', clearProjectMemoryConfirm: 'Clear learned grouping preferences from this device?', projectMemoryCleared: 'Learned grouping preferences cleared.', groupColorGrey: 'Grey', groupColorBlue: 'Blue', groupColorCyan: 'Cyan', groupColorGreen: 'Green', groupColorYellow: 'Yellow', groupColorOrange: 'Orange', groupColorRed: 'Red', groupColorPink: 'Pink', groupColorPurple: 'Purple',
  },
  zh: {
    liveTabs: '当前标签', stash: '暂存', stashLibrary: '暂存库', dropToStash: '拖到这里暂存', findTabOrProject: '搜索标签或项目', tabActions: '标签操作',
    groupTabs: '智能分组', cleanUp: '清理', stashWindow: '暂存窗口', keepPinnedActive: '保留固定和当前标签', stashAllTabs: '暂存全部标签', includePinnedActive: '包含固定和当前标签',
    quietlySynced: '已同步', deepScanOn: '深度扫描已开启', adaptiveContext: '智能分析', tabWorkspace: '标签工作区', openSettings: '打开设置', zenTabSections: 'Zen Tab 区域', browserWindows: '浏览器窗口',
    window: '窗口 {index}', privateWindow: '隐身窗口', scanningAllPageContext: '正在扫描页面内容', enrichingUncertainTabs: '正在补充不确定标签', findingLowValueTabs: '正在查找低价值标签', workingQuietly: '正在安静处理',
    stashingGroup: '正在暂存分组', stashingTab: '正在暂存标签', stashingWindow: '正在暂存窗口', stashingAllTabs: '正在暂存全部标签', stashingSelectedTabs: '正在暂存选中标签', stashingUngrouped: '正在暂存未分组标签',
    projectContextEnriched: '已用页面摘要补充项目上下文。', projectContextMetadata: '已根据标签标题和链接建立项目上下文。', actionFailed: '操作失败。', couldNotAnalyzeWindow: '无法分析这个窗口。', couldNotScanWindow: '无法扫描这个窗口。',
    tabsStashed: '已暂存 {count} 个标签。', tabsClosed: '已关闭 {count} 个标签。', tabsClosedWithSkipped: '已关闭 {closed} 个标签，{skipped} 个因状态变化而跳过。', tabsCount: '{count} 个标签', groupsCreated: '已创建 {count} 个项目分组。', couldNotStashTabs: '无法暂存这些标签。', couldNotCloseTabs: '无法关闭选中的标签。', lastActionRestored: '已恢复上一步操作。', nothingToUndo: '没有可撤销的操作。', tabsRestoredWithSkipped: '已恢复 {created} 个标签，{failed} 个无法恢复。', restoringTabs: '正在恢复标签',
    deepScanReady: '深度扫描已准备好。', adaptiveMetadataEnabled: '将继续使用智能元数据分析。', permissionDenied: 'Chrome 没有授予页面摘要权限。', openingZenTab: '正在打开 Zen Tab', connectingToTabs: '正在连接 Chrome 标签…',
    noMatchingTabs: '没有匹配的标签', clearWindow: '窗口终于清爽了。', tryShorterTitle: '试试更短的标题或域名。', openTabToAppear: '打开一个标签，它会立即出现在这里。', selected: '已选择', selectionMode: '选择模式 · 点击行来切换', exitSelection: '退出选择模式', moveTabToStart: '移到最前面', untitledGroup: '未命名分组', ungrouped: '未分组', untitledTab: '未命名标签', selectTab: '选择 {title}', deselectTab: '取消选择 {title}', selectGroup: '选择分组 {name}', clickToSelect: '点击选择或取消选择', actionsFor: '{title} 的操作', playingAudio: '正在播放声音', discarded: '已休眠', pinned: '已固定', mute: '静音', unmute: '取消静音', pin: '固定', unpin: '取消固定', close: '关闭', done: '完成', undo: '撤销', dismiss: '关闭提示',
    projectMap: '项目地图', suggestedGroups: '{count} 个建议分组', checkTabsEvidence: '创建浏览器分组前，请检查标签和依据。不确定的标签会保留在分组外。', suggestionsToReview: '请检查分组建议', tabsNeedMoreContext: '{count} 个标签需要更多上下文', noValidGroups: '请至少选择一个包含两个或更多标签的分组。', invalidGroupName: '项目名称需为 1 到 42 个字符。', reviewBeforeApplying: '确认后应用', keepAsIs: '保持不变', createGroups: '创建 {count} 个分组', applying: '正在应用…', lowValueScan: '低价值扫描', possibleCleanups: '{count} 个可能需要清理的标签', nothingCloses: '只有在你确认后才会关闭。受保护页面会显示，但不能选择。', protectedPages: '保守清理', conservative: '不包含当前、固定、本地或受保护页面', noProtectedPages: '没有包含受保护页面', leaveEverything: '全部保留', noSafeCleanup: '没有安全的清理候选项。', contextIntentional: '你打开的内容看起来都是有意保留的。',
    recoverableContext: '可恢复上下文', stashLibraryDescription: '会话会保存在本地，直到你决定删除它们。', stashSearch: '搜索已保存会话', noMatchingStashes: '没有匹配的会话', saved: '已保存', nextFocus: '下一个专注点，从这里开始。', restore: '恢复', restoreTab: '恢复标签', restoreGroup: '恢复分组', delete: '删除', renameStash: '重命名暂存', expandStash: '展开暂存', collapseStash: '收起暂存', stashRenamed: '暂存已重命名。', invalidStashName: '暂存名称需为 1 到 80 个字符。', tabsOpening: '正在新窗口打开 {count} 个标签。', stashDeleted: '暂存已删除。', couldNotRestoreStash: '无法恢复暂存。', couldNotDeleteStash: '无法删除暂存。', stashEmptyDescription: '暂存窗口或选中的标签，之后可以随时恢复。', pageNoLongerAvailable: '页面已不可用', keptAside: '有 {count} 个标签暂不分组。它们的项目信号太弱或存在冲突，暂时无法安全判断。', couldNotSaveGroqKey: '无法保存 Groq Key。', groqKeySaved: 'Groq Key 已保存在本地。',
    controlRoom: '控制中心', settings: '设置', settingsDescription: '用几个小设置，让自动化始终在你的掌控之中。', language: '语言', languageDescription: '选择 Zen Tab 的界面语言。', theme: '主题', themeDescription: '跟随 Chrome，也可以固定外观。', systemTheme: '系统（跟随 Chrome）', lightTheme: '浅色', darkTheme: '深色', duplicateGuard: '重复标签防护', catchRepeated: '重复页面出现时自动提醒。', matchScope: '匹配范围', allNormalWindows: '所有普通窗口', currentWindowOnly: '仅当前窗口', deepScanAll: '扫描所有标签', deepScanDescription: '点击智能分组时读取最多 300 个页面摘要。', deepScanPrivacy: '默认关闭。有权限时，智能分析最多读取 32 个上下文不足的标签。', aiProvider: 'AI 服务', localAutomatic: '本地 / 自动', groqByok: 'Groq（使用自己的 Key）', groqApiKey: 'Groq API Key', savedLocally: '已保存在本地 · 输入新的 Key 可替换', clearApiKey: '清除 API Key', groqPrivacy: '与界面快照分开保存。只有你选择 Groq 时，才会发送元数据和请求的页面摘要。', groqPermissionDenied: '没有获得 Groq 网络权限，已继续使用本地模式。', couldNotSaveSettings: '设置保存失败。', protectedDomains: '受保护域名', protectedDomainsDescription: '永远不要为这些域名推荐清理。', protectedDomainsPlaceholder: 'figma.com, docs.google.com', settingsFootnote: 'Zen Tab 不承诺显示精确的单标签内存，而是使用休眠状态和安全规则。', strongMatch: '高度匹配', possibleMatch: '可能匹配', needsReview: '需要检查', severalSignals: '多个信号指向同一个项目。', someSignals: '部分信号相似，建议在分组前检查依据。', limitedContext: '上下文不足或存在冲突。', moveTo: '移动到', unclassified: '未分类', renameGroup: '重命名分组', changeGroupColor: '更改分组颜色', ungroup: '取消分组', groupUpdated: '分组已更新。', clearProjectMemory: '清除已学习的分组偏好', clearProjectMemoryDescription: '只有你明确确认过的项目选择会保存在本地，用于改善后续建议。', clearProjectMemoryConfirm: '清除这台设备上的已学习分组偏好？', projectMemoryCleared: '已清除已学习的分组偏好。', groupColorGrey: '灰色', groupColorBlue: '蓝色', groupColorCyan: '青色', groupColorGreen: '绿色', groupColorYellow: '黄色', groupColorOrange: '橙色', groupColorRed: '红色', groupColorPink: '粉色', groupColorPurple: '紫色',
  },
};

export function createTranslator(language: Language): Translator {
  const dictionary = translations[language] ?? translations.en;
  return (key, values = {}) => {
    const template = dictionary[key] ?? translations.en[key] ?? key;
    return template.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
  };
}
