import { Language } from '../shared/types';

export type TranslationKey =
  | 'liveTabs' | 'tabs' | 'stash' | 'stashLibrary' | 'dropToStash' | 'findTabOrProject' | 'tabActions'
  | 'bookmarks' | 'moreActions' | 'organizeMenu'
  | 'groupSelected' | 'analyzeSelection' | 'fileToBookmarks' | 'groupedTabs' | 'couldNotGroupTabs' | 'needTwoTabsToGroup'
  | 'groupTabs' | 'cleanUp' | 'stashWindow' | 'keepPinnedActive' | 'stashAllTabs' | 'includePinnedActive'
  | 'openSettings'
  | 'zenTabSections' | 'browserWindows' | 'window' | 'privateWindow' | 'scanningAllPageContext' | 'enrichingUncertainTabs' | 'findingLowValueTabs' | 'workingQuietly'
  | 'stashingGroup' | 'stashingTab' | 'stashingWindow' | 'stashingAllTabs' | 'stashingSelectedTabs' | 'stashingUngrouped'
  | 'projectContextEnriched' | 'projectContextMetadata' | 'actionFailed' | 'couldNotAnalyzeWindow' | 'couldNotScanWindow'
  | 'tabsStashed' | 'tabsClosed' | 'tabsClosedWithSkipped' | 'tabsCount' | 'tabSingle' | 'groupsCreated' | 'couldNotStashTabs' | 'couldNotCloseTabs' | 'lastActionRestored' | 'nothingToUndo' | 'tabsRestoredWithSkipped' | 'restoringTabs'
  | 'deepScanReady' | 'adaptiveMetadataEnabled' | 'permissionDenied' | 'openingZenTab' | 'connectingToTabs'
  | 'noMatchingTabs' | 'clearWindow' | 'tryShorterTitle' | 'openTabToAppear' | 'selected' | 'selectionMode'
  | 'exitSelection' | 'moveTabToStart' | 'untitledGroup' | 'ungrouped' | 'untitledTab' | 'selectTab' | 'deselectTab' | 'selectGroup'
  | 'clickToSelect' | 'actionsFor' | 'playingAudio' | 'discarded' | 'discardTab' | 'pinned' | 'mute' | 'unmute' | 'pin' | 'unpin' | 'activate' | 'close' | 'done' | 'undo' | 'dismiss'
  | 'selectAll' | 'closeAll' | 'moveTabToEnd'
  | 'projectMap' | 'suggestedGroups' | 'checkTabsEvidence' | 'suggestionsToReview' | 'tabsNeedMoreContext' | 'noValidGroups' | 'invalidGroupName'
  | 'reviewBeforeApplying' | 'keepAsIs' | 'createGroups' | 'applying' | 'lowValueScan' | 'possibleCleanups'
  | 'nothingCloses' | 'protectedPages' | 'conservative' | 'leaveEverything' | 'noSafeCleanup'
  | 'contextIntentional' | 'recoverableContext' | 'stashLibraryDescription' | 'stashSearch' | 'noMatchingStashes' | 'saved' | 'nextFocus' | 'restore' | 'restoreTab' | 'restoreGroup' | 'delete' | 'renameStash' | 'expandStash' | 'collapseStash' | 'stashRenamed' | 'invalidStashName'
  | 'tabsOpening' | 'stashDeleted' | 'couldNotRestoreStash' | 'couldNotDeleteStash' | 'stashEmptyDescription' | 'pageNoLongerAvailable' | 'keptAside' | 'controlRoom' | 'settings'
  | 'settingsDescription' | 'language' | 'languageDescription' | 'theme' | 'themeDescription' | 'systemTheme' | 'lightTheme'
  | 'darkTheme' | 'atmosphere' | 'atmosphereDescription' | 'duplicateGuard' | 'catchRepeated' | 'matchScope' | 'allNormalWindows' | 'currentWindowOnly'
  | 'deepScanAll' | 'deepScanDescription' | 'deepScanPrivacy' | 'aiProvider' | 'localAutomatic'
  | 'savedLocally' | 'clearApiKey' | 'couldNotSaveSettings' | 'protectedDomains' | 'protectedDomainsDescription' | 'protectedDomainsPlaceholder'
  | 'settingsFootnote' | 'strongMatch' | 'possibleMatch' | 'needsReview' | 'severalSignals' | 'someSignals' | 'limitedContext' | 'moveTo' | 'unclassified' | 'renameGroup' | 'changeGroupColor' | 'ungroup' | 'groupUpdated' | 'clearProjectMemory' | 'clearProjectMemoryDescription' | 'clearProjectMemoryConfirm' | 'projectMemoryCleared' | 'groupColorGrey' | 'groupColorBlue' | 'groupColorCyan' | 'groupColorGreen' | 'groupColorYellow' | 'groupColorOrange' | 'groupColorRed' | 'groupColorPink' | 'groupColorPurple'
  | 'ignoredDomains' | 'ignoredDomainsDescription' | 'ignoredDomainsPlaceholder' | 'incognitoWindows' | 'incognitoWindowsDescription'
  | 'openaiCompatible' | 'openaiBaseUrl' | 'openaiModel' | 'openaiApiKey' | 'openaiPrivacy' | 'openaiPermissionDenied' | 'couldNotSaveApiKey' | 'apiKeySaved' | 'openaiHint'
  | 'autoDiscard' | 'autoDiscardDescription' | 'autoDiscardAfter' | 'autoDiscardInspect' | 'autoDiscardInspectDescription' | 'minutes15' | 'minutes30' | 'minutes60' | 'minutes120'
  | 'commandPalette' | 'commandPalettePlaceholder' | 'cmdStashWindow' | 'cmdStashAll' | 'cmdGroup' | 'cmdCleanup' | 'cmdSettings' | 'cmdFocusSearch' | 'cmdStashLibrary' | 'cmdBookmarks' | 'cmdUndo' | 'cmdExportWindow' | 'cmdJumpTab' | 'cmdJumpStash' | 'cmdJumpBookmark' | 'cmdSwitchWindow' | 'noMatchingCommands'
  | 'paletteBadgeActive' | 'paletteBadgeTab' | 'paletteBadgeBookmark' | 'paletteBadgeStash' | 'paletteBadgeWindow' | 'paletteBadgeCommand' | 'activeTab'
  | 'settingsAppearance' | 'settingsTabs' | 'settingsAi' | 'settingsPrivacy' | 'collapseFolder' | 'expandFolder' | 'dropToFile' | 'emptyFolderDropHint' | 'bookmarksCreated'
  | 'exportJson' | 'exportMarkdown' | 'exportWindow' | 'importFile' | 'importOneTab' | 'importedStashes' | 'couldNotImport' | 'noImportEntries' | 'oneTabImportName' | 'windowExportName' | 'importJsonTooltip' | 'importOneTabTooltip'
  | 'recentlyClosed' | 'restoreClosed' | 'closedWindow' | 'closedTab' | 'couldNotListSessions' | 'showAllRecent' | 'showLessRecent'
  | 'playingNow' | 'muteAllAudio' | 'jumpToAudio' | 'cancel'
  | 'couldNotLoadBookmarks' | 'bookmarkSearchResults' | 'bookmarkInbox' | 'bookmarksFiled' | 'noDuplicateBookmarks' | 'duplicateBookmarksRemoved'
  | 'bookmarkSummaryUnavailable' | 'bookmarkSummarySaved' | 'loadingBookmarks' | 'bookmarkPermissionTitle' | 'bookmarkPermissionBody' | 'grantBookmarkAccess'
  | 'bookmarkLibraryDescription' | 'findDuplicates' | 'bookmarkSuggestedFolder' | 'bookmarkChooseFolder' | 'review' | 'noMatchingBookmarks'
  | 'noBookmarksYet' | 'tryDifferentBookmarkSearch' | 'saveBookmarkToAppear' | 'enrichBookmark' | 'openBookmark' | 'fileBookmark' | 'chooseBookmarkFolder'
  | 'noBookmarkFolders' | 'bookmarkDedupTitle' | 'bookmarkDedupEyebrow' | 'bookmarkDedupDescription' | 'bookmarkDedupKeep' | 'bookmarkDedupRemove' | 'removeDuplicateBookmarks'
  | 'editBookmark' | 'deleteBookmark' | 'newBookmarkFolder' | 'renameBookmarkFolder' | 'deleteBookmarkFolder' | 'openAllBookmarks'
  | 'bookmarkChipAll' | 'bookmarkChipInbox' | 'bookmarkChipDuplicates' | 'bookmarkTitleLabel' | 'bookmarkUrlLabel' | 'saveBookmarkEdit'
  | 'invalidBookmarkUrl' | 'deleteFolderConfirm' | 'openAllBookmarksConfirm' | 'bookmarkFolderName' | 'bookmarksSkipped'
  | 'reviewInbox' | 'skipBookmark' | 'newFolderInReview' | 'newFolderParent' | 'bookmarkInboxHint'
  | 'bookmarkOrganize' | 'unfiledBookmarkCount' | 'reviewUnfiled' | 'bookmarkMoved' | 'bookmarkOrganizeDescription' | 'fileSuggestedBookmarks' | 'noFilingSuggestions' | 'organizeInboxTitle'
  | 'organizeClustersTitle' | 'organizeCreateFolder' | 'organizeExistingFolder' | 'organizeClusterCount' | 'applyOrganizePlan' | 'noOrganizeSuggestions' | 'bookmarksOrganized' | 'organizeMoreBookmarks'
  | 'organizeByTopic' | 'organizeAnalyzing' | 'organizeNeedsModel' | 'organizeAnalyzedCount' | 'organizeShowHostClusters' | 'organizeTopicFailed'
  | 'organizeSnapshotsTitle' | 'organizeSnapshotMeta' | 'organizeRestore' | 'organizeRestoreConfirm' | 'organizeRestored' | 'organizeSnapshotSaveFailed' | 'organizeNothingToApply'
  | 'organizeScopeUnfiled' | 'organizeScopeBar' | 'organizeScopeOther' | 'organizeScopeAll' | 'organizeScopeLabel' | 'organizeTargetFolder' | 'organizeNewFolderLabel' | 'organizeIncludedCount' | 'organizeCandidateCount' | 'organizeShowLess'
  | 'exportBookmarks' | 'exportAddsNotReplaces' | 'exportNetscapeHtml' | 'downloadExport'
  | 'builtInAi' | 'builtInAiUnsupported' | 'builtInAiUnavailable' | 'builtInAiDownloadable' | 'builtInAiDownloading' | 'builtInAiAvailable' | 'builtInAiDownload' | 'builtInAiDownloadProgress';

type TranslationValues = Record<string, string | number>;
export type Translator = (key: TranslationKey, values?: TranslationValues) => string;

const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    liveTabs: 'Live tabs', tabs: 'Tabs', stash: 'Stash', stashLibrary: 'Stash library', dropToStash: 'Drop to stash', findTabOrProject: 'Find a tab, stash, or bookmark ({shortcut})', tabActions: 'Tab actions',
    bookmarks: 'Bookmarks', moreActions: 'More actions', organizeMenu: 'Organize',
    groupSelected: 'Group selected', analyzeSelection: 'Analyze selection', fileToBookmarks: 'Save to bookmarks', groupedTabs: 'Grouped {count} tabs.', couldNotGroupTabs: 'Could not group those tabs.', needTwoTabsToGroup: 'Select at least two unpinned tabs to group.',
    groupTabs: 'Group tabs', cleanUp: 'Clean up', stashWindow: 'Stash window', keepPinnedActive: 'Keep pinned and active tabs', stashAllTabs: 'Stash all tabs', includePinnedActive: 'Include pinned and active tabs', openSettings: 'Open settings', zenTabSections: 'Zen Tab sections', browserWindows: 'Browser windows',
    window: 'Window {index}', privateWindow: 'Private window', scanningAllPageContext: 'Scanning all page context', enrichingUncertainTabs: 'Enriching uncertain tabs', findingLowValueTabs: 'Finding low-value tabs', workingQuietly: 'working quietly',
    stashingGroup: 'Stashing group', stashingTab: 'Stashing tab', stashingWindow: 'Stashing window', stashingAllTabs: 'Stashing all tabs', stashingSelectedTabs: 'Stashing selected tabs', stashingUngrouped: 'Stashing ungrouped tabs',
    projectContextEnriched: 'Project context enriched with page summaries.', projectContextMetadata: 'Project context built from tab metadata.', actionFailed: 'Action failed.', couldNotAnalyzeWindow: 'Could not analyze this window.', couldNotScanWindow: 'Could not scan this window.',
    tabsStashed: '{count} tabs stashed.', tabsClosed: '{count} tabs closed.', tabsClosedWithSkipped: '{closed} tabs closed; {skipped} skipped because their state changed.', tabsCount: '{count} tabs', tabSingle: '1 tab', groupsCreated: '{count} project groups created.', couldNotStashTabs: 'Could not stash those tabs.', couldNotCloseTabs: 'Could not close selected tabs.', lastActionRestored: 'Last action restored.', nothingToUndo: 'Nothing to undo.', tabsRestoredWithSkipped: '{created} tabs restored; {failed} could not be restored.', restoringTabs: 'Restoring tabs',
    deepScanReady: 'Deep scan all is ready.', adaptiveMetadataEnabled: 'Adaptive metadata analysis remains enabled.', permissionDenied: 'Chrome did not grant page-summary access.', openingZenTab: 'Opening Zen Tab', connectingToTabs: 'Connecting to Chrome tabs…',
    noMatchingTabs: 'No matching tabs', clearWindow: 'A clear window, for once.', tryShorterTitle: 'Try a shorter title or domain.', openTabToAppear: 'Open a tab and it will appear here instantly.', selected: 'selected', selectionMode: 'Selection mode · click rows to toggle', exitSelection: 'Exit selection mode', moveTabToStart: 'Move tab to start', moveTabToEnd: 'Move tab to end', untitledGroup: 'Untitled group', ungrouped: 'Ungrouped', untitledTab: 'Untitled tab', selectTab: 'Select {title}', deselectTab: 'Deselect {title}', selectGroup: 'Select group {name}', selectAll: 'Select all', closeAll: 'Close all', clickToSelect: 'Click to select or deselect', actionsFor: 'Actions for {title}', playingAudio: 'Playing audio', discarded: 'Discarded', discardTab: 'Sleep tab', pinned: 'Pinned', mute: 'Mute', unmute: 'Unmute', pin: 'Pin', unpin: 'Unpin', activate: 'Activate', close: 'Close', done: 'Done', undo: 'Undo', dismiss: 'Dismiss',
    projectMap: 'PROJECT MAP', suggestedGroups: '{count} suggested groups', checkTabsEvidence: 'Check the tabs and evidence before creating browser groups. Uncertain tabs stay out.', suggestionsToReview: 'Suggestions to review', tabsNeedMoreContext: '{count} tabs need more context', noValidGroups: 'Select at least one group with two or more tabs.', invalidGroupName: 'Project names must be between 1 and 42 characters.', reviewBeforeApplying: 'Review before applying', keepAsIs: 'Keep as-is', createGroups: 'Create {count} groups', applying: 'Applying…', lowValueScan: 'LOW-VALUE SCAN', possibleCleanups: '{count} possible cleanups', nothingCloses: 'Nothing closes until you choose it. Protected pages are shown but cannot be selected.', protectedPages: 'Conservative by design', conservative: 'no active, pinned, local, or protected pages included', leaveEverything: 'Leave everything', noSafeCleanup: 'No safe cleanup candidates.', contextIntentional: 'Your open context looks intentional.',
    recoverableContext: 'RECOVERABLE CONTEXT', stashLibraryDescription: 'Sessions live locally until you decide they should disappear.', stashSearch: 'Search saved sessions', noMatchingStashes: 'No matching sessions', saved: 'saved', nextFocus: 'Your next focus starts here.', restore: 'Restore', restoreTab: 'Restore tab', restoreGroup: 'Restore group', delete: 'Delete', renameStash: 'Rename stash', expandStash: 'Expand stash', collapseStash: 'Collapse stash', stashRenamed: 'Stash renamed.', invalidStashName: 'Use a stash name between 1 and 80 characters.', tabsOpening: '{count} tabs are opening in a new window.', stashDeleted: 'Stash deleted.', couldNotRestoreStash: 'Could not restore stash.', couldNotDeleteStash: 'Could not delete stash.', stashEmptyDescription: 'Stash a window or selected tabs to keep them for later.', pageNoLongerAvailable: 'Page no longer available', keptAside: '{count} kept aside. Their project signal is too weak or conflicted to make a safe call.',
    controlRoom: 'CONTROL ROOM', settings: 'Settings', settingsDescription: 'Small controls that keep automation inside your comfort zone.', language: 'Language', languageDescription: 'Choose the language for Zen Tab.', theme: 'Theme', themeDescription: 'Follow Chrome or choose a fixed appearance.', systemTheme: 'System (Chrome)', lightTheme: 'Light', darkTheme: 'Dark', atmosphere: 'Atmosphere', atmosphereDescription: 'A quiet field behind the panel. Turn off for a flatter look.', duplicateGuard: 'Duplicate guard', catchRepeated: 'Catch repeated pages as they appear.', matchScope: 'Match scope', allNormalWindows: 'All normal windows', currentWindowOnly: 'Current window only', deepScanAll: 'Deep scan all tabs', deepScanDescription: 'Read up to 300 page summaries during Group tabs.', deepScanPrivacy: 'Off by default. Adaptive summaries use up to 32 uncertain tabs when access is available.', aiProvider: 'AI provider', localAutomatic: 'Local / automatic', savedLocally: 'Saved locally · enter to replace', clearApiKey: 'Clear API key', couldNotSaveSettings: 'Could not save that setting.', protectedDomains: 'Protected domains', protectedDomainsDescription: 'Never suggest cleanup for these hosts.', protectedDomainsPlaceholder: 'figma.com, docs.google.com', settingsFootnote: 'Zen Tab never promises exact per-tab memory. It uses discard state and safe heuristics instead.', strongMatch: 'Strong match', possibleMatch: 'Possible match', needsReview: 'Needs review', severalSignals: 'Several signals point to the same project.', someSignals: 'Some signals overlap. Review the evidence before grouping.', limitedContext: 'Context is limited or conflicting.', moveTo: 'Move to', unclassified: 'Unclassified', renameGroup: 'Rename group', changeGroupColor: 'Change group color', ungroup: 'Ungroup', groupUpdated: 'Group updated.', clearProjectMemory: 'Clear learned grouping preferences', clearProjectMemoryDescription: 'Only explicit project choices are stored locally to improve future suggestions.', clearProjectMemoryConfirm: 'Clear learned grouping preferences from this device?', projectMemoryCleared: 'Learned grouping preferences cleared.',     groupColorGrey: 'Grey', groupColorBlue: 'Blue', groupColorCyan: 'Cyan', groupColorGreen: 'Green', groupColorYellow: 'Yellow', groupColorOrange: 'Orange', groupColorRed: 'Red', groupColorPink: 'Pink', groupColorPurple: 'Purple',
    ignoredDomains: 'Ignored domains', ignoredDomainsDescription: 'Duplicate guard skips these hosts.', ignoredDomainsPlaceholder: 'mail.google.com, calendar.google.com', incognitoWindows: 'Private windows', incognitoWindowsDescription: 'Allow duplicate guard, grouping, cleanup, and stash in private windows.',
    openaiCompatible: 'OpenAI-compatible (BYOK)', openaiBaseUrl: 'API base URL', openaiModel: 'Model', openaiApiKey: 'API key', openaiPrivacy: 'Stored locally. Metadata is sent only after you choose this provider. Groq, OpenAI, and Ollama all work with this endpoint shape.', openaiPermissionDenied: 'Network access for that API host was not granted; local mode remains enabled.', couldNotSaveApiKey: 'Could not save the API key.', apiKeySaved: 'API key saved locally.', openaiHint: 'Examples: https://api.groq.com/openai/v1 · https://api.openai.com/v1 · http://127.0.0.1:11434/v1',
    autoDiscard: 'Auto-discard idle tabs', autoDiscardDescription: 'Off by default. Sleeps idle tabs on a one-minute alarm. Active, pinned, audible, local, and protected pages stay awake.', autoDiscardAfter: 'Idle for', autoDiscardInspect: 'Skip tabs with unsaved input', autoDiscardInspectDescription: 'Optional page check for dirty forms, editors, and playing media. Needs page-access permission. If permission is missing, idle tabs are left awake.', minutes15: '15 minutes', minutes30: '30 minutes', minutes60: '1 hour', minutes120: '2 hours',
    commandPalette: 'Command palette', commandPalettePlaceholder: 'Type a command, tab, stash, or bookmark', cmdStashWindow: 'Stash current window', cmdStashAll: 'Stash all tabs in window', cmdGroup: 'Group tabs', cmdCleanup: 'Clean up low-value tabs', cmdSettings: 'Open settings', cmdFocusSearch: 'Focus search', cmdStashLibrary: 'Open stash library', cmdBookmarks: 'Open bookmarks', cmdUndo: 'Undo last action', cmdExportWindow: 'Export current window as JSON', cmdJumpTab: 'Switch to tab', cmdJumpStash: 'Open stash', cmdJumpBookmark: 'Open bookmark', cmdSwitchWindow: 'Switch window', noMatchingCommands: 'No matching commands, tabs, or bookmarks.',
    paletteBadgeActive: 'Active', paletteBadgeTab: 'Tab', paletteBadgeBookmark: 'Bookmark', paletteBadgeStash: 'Stash', paletteBadgeWindow: 'Window', paletteBadgeCommand: 'Command', activeTab: 'Active tab',
    settingsAppearance: 'Appearance', settingsTabs: 'Tabs', settingsAi: 'AI', settingsPrivacy: 'Privacy', collapseFolder: 'Collapse folder', expandFolder: 'Expand folder', dropToFile: 'Drop to bookmark', emptyFolderDropHint: 'Empty folder · Drop here', bookmarksCreated: 'Saved {count} bookmarks.',
    exportJson: 'Export JSON', exportMarkdown: 'Export Markdown', exportWindow: 'Export window', importFile: 'Import JSON', importOneTab: 'Import OneTab text', importedStashes: 'Imported {count} sessions into the stash library.', couldNotImport: 'Could not import that file.', noImportEntries: 'No URLs were found in that text.', oneTabImportName: 'OneTab import', windowExportName: 'Window {index}', importJsonTooltip: 'Restore tab sessions from an exported Zen Tab JSON file', importOneTabTooltip: 'Import tabs from OneTab export format (URL | Title)',
    recentlyClosed: 'Recently closed', restoreClosed: 'Restore', closedWindow: 'Closed window', closedTab: 'Closed tab', couldNotListSessions: 'Could not read recently closed sessions.', showAllRecent: 'Show all {count} closed items', showLessRecent: 'Show less',
    playingNow: 'Playing now', muteAllAudio: 'Mute all', jumpToAudio: 'Jump to audio tab', cancel: 'Cancel',
    couldNotLoadBookmarks: 'Could not load bookmarks.', bookmarkSearchResults: 'Search results', bookmarkInbox: 'Inbox', bookmarksFiled: '{count} bookmark filed in {folder}.', noDuplicateBookmarks: 'No duplicate bookmarks found.', duplicateBookmarksRemoved: '{count} duplicate bookmarks removed.', bookmarkSummaryUnavailable: 'A page summary is not available for this bookmark.', bookmarkSummarySaved: 'Page summary saved for bookmark search.', loadingBookmarks: 'Loading bookmarks…', bookmarkPermissionTitle: 'Connect your bookmarks', bookmarkPermissionBody: 'Zen Tab needs bookmark access to search and file your saved pages.', grantBookmarkAccess: 'Grant bookmark access', bookmarkLibraryDescription: '{count} saved pages', findDuplicates: 'Find duplicates', bookmarkSuggestedFolder: 'Suggested folder: {folder}', bookmarkChooseFolder: 'Choose where to file this new bookmark.', review: 'Review', noMatchingBookmarks: 'No matching bookmarks', noBookmarksYet: 'No bookmarks yet', tryDifferentBookmarkSearch: 'Try a title, domain, folder, or saved page summary.', saveBookmarkToAppear: 'Save a page in Chrome and it will appear here.', enrichBookmark: 'Add open-page context to search', openBookmark: 'Open', fileBookmark: 'File', chooseBookmarkFolder: 'Choose a folder', noBookmarkFolders: 'Create a bookmark folder first', bookmarkDedupTitle: 'Review duplicate bookmarks', bookmarkDedupEyebrow: 'BOOKMARK CLEANUP', bookmarkDedupDescription: 'The selected copies are kept. Nothing is removed until you confirm.', bookmarkDedupKeep: 'Keep in {folder}', bookmarkDedupRemove: 'Remove {count} extra copies', removeDuplicateBookmarks: 'Remove {count} duplicates',
    editBookmark: 'Edit', deleteBookmark: 'Delete', newBookmarkFolder: 'New folder', renameBookmarkFolder: 'Rename', deleteBookmarkFolder: 'Delete folder', openAllBookmarks: 'Open all',
    bookmarkChipAll: 'All', bookmarkChipInbox: 'Inbox', bookmarkChipDuplicates: 'Duplicates', bookmarkTitleLabel: 'Name', bookmarkUrlLabel: 'URL', saveBookmarkEdit: 'Save',
    invalidBookmarkUrl: 'Enter a valid URL.', deleteFolderConfirm: 'Delete this folder and everything inside?', openAllBookmarksConfirm: 'Open {count} bookmarks?', bookmarkFolderName: 'Folder name', bookmarksSkipped: 'Skipped {count}.',
    reviewInbox: 'Review Inbox', skipBookmark: 'Skip', newFolderInReview: 'New folder', newFolderParent: 'Parent folder', bookmarkInboxHint: 'Not in a folder yet.',
    bookmarkOrganize: 'Organize', unfiledBookmarkCount: '{count} in Inbox', reviewUnfiled: 'Review Inbox', bookmarkMoved: 'Bookmark moved.', bookmarkOrganizeDescription: 'Suggested folders and duplicate cleanup. Nothing writes until you confirm.', fileSuggestedBookmarks: 'File {count} suggested', noFilingSuggestions: 'No folder matches yet. Review Inbox to file by hand.', organizeInboxTitle: 'Inbox filing',
    organizeClustersTitle: 'Suggested folders', organizeCreateFolder: 'New folder', organizeExistingFolder: 'Existing folder', organizeClusterCount: '{count} bookmarks', applyOrganizePlan: 'Apply {count} changes', noOrganizeSuggestions: 'No folder groups yet. Sites need at least two bookmarks, or a matching folder.', bookmarksOrganized: 'Organized {count} bookmarks.', organizeMoreBookmarks: '+{count} more',
    organizeByTopic: 'Organize by topic', organizeAnalyzing: 'Finding topic folders…', organizeNeedsModel: 'Topic organize needs an on-device model or an API key in Settings.', organizeAnalyzedCount: 'Analyzed {analyzed} of {eligible} bookmarks', organizeShowHostClusters: 'Show site groups only', organizeTopicFailed: 'Topic analysis failed. Site groups are still available.',
    organizeSnapshotsTitle: 'Restore points', organizeSnapshotMeta: '{count} bookmarks · {days} days left', organizeRestore: 'Restore', organizeRestoreConfirm: 'Move these bookmarks back to where they were at {time}? Bookmarks you moved afterward will also go back.', organizeRestored: 'Restored {count} bookmarks.', organizeSnapshotSaveFailed: 'Organized, but the 7-day restore point could not be saved.', organizeNothingToApply: 'Nothing to apply.',
    organizeScopeUnfiled: 'Unfiled (Recommended)', organizeScopeBar: 'Bookmarks bar', organizeScopeOther: 'Other bookmarks', organizeScopeAll: 'All bookmarks', organizeScopeLabel: 'Scope', organizeTargetFolder: 'Target folder', organizeNewFolderLabel: 'New: {name}', organizeIncludedCount: 'Apply {count} selected', organizeCandidateCount: '{count} candidate bookmarks', organizeShowLess: 'Show less',
    exportBookmarks: 'Export', exportAddsNotReplaces: 'Importing this HTML adds a new folder tree. It does not replace your existing bookmarks.', exportNetscapeHtml: 'Export HTML', downloadExport: 'Download',
    builtInAi: 'On-device model', builtInAiUnsupported: 'Not available in this Chrome.', builtInAiUnavailable: 'Unavailable on this device.', builtInAiDownloadable: 'Ready to download when grouping needs it.', builtInAiDownloading: 'Downloading the on-device model…', builtInAiAvailable: 'Available offline for grouping.', builtInAiDownload: 'Download on-device model', builtInAiDownloadProgress: 'Downloading on-device model… {percent}%',
  },
  zh: {
    liveTabs: '当前标签', tabs: '标签', stash: '暂存', stashLibrary: '暂存库', dropToStash: '拖到这里暂存', findTabOrProject: '搜索标签、暂存或书签 ({shortcut})', tabActions: '标签操作',
    bookmarks: '书签', moreActions: '更多操作', organizeMenu: '整理',
    groupSelected: '将所选标签成组', analyzeSelection: '分析所选', fileToBookmarks: '保存到书签', groupedTabs: '已将 {count} 个标签成组。', couldNotGroupTabs: '无法将这些标签成组。', needTwoTabsToGroup: '请至少选择两个未固定的标签再成组。',
    groupTabs: '智能分组', cleanUp: '清理', stashWindow: '暂存窗口', keepPinnedActive: '保留固定和当前标签', stashAllTabs: '暂存全部标签', includePinnedActive: '包含固定和当前标签', openSettings: '打开设置', zenTabSections: 'Zen Tab 区域', browserWindows: '浏览器窗口',
    window: '窗口 {index}', privateWindow: '无痕窗口', scanningAllPageContext: '正在扫描页面内容', enrichingUncertainTabs: '正在分析不确定标签', findingLowValueTabs: '正在查找闲置标签', workingQuietly: '正在后台处理',
    stashingGroup: '正在暂存分组', stashingTab: '正在暂存标签', stashingWindow: '正在暂存窗口', stashingAllTabs: '正在暂存全部标签', stashingSelectedTabs: '正在暂存选中标签', stashingUngrouped: '正在暂存未分组标签',
    projectContextEnriched: '已用页面摘要建立项目上下文。', projectContextMetadata: '已根据标签标题和链接建立项目上下文。', actionFailed: '操作失败。', couldNotAnalyzeWindow: '无法分析这个窗口。', couldNotScanWindow: '无法扫描这个窗口。',
    tabsStashed: '已暂存 {count} 个标签。', tabsClosed: '已关闭 {count} 个标签。', tabsClosedWithSkipped: '已关闭 {closed} 个标签，{skipped} 个因状态变化而跳过。', tabsCount: '{count} 个标签', tabSingle: '1 个标签', groupsCreated: '已创建 {count} 个项目分组。', couldNotStashTabs: '无法暂存这些标签。', couldNotCloseTabs: '无法关闭选中的标签。', lastActionRestored: '已恢复上一步操作。', nothingToUndo: '没有可撤销的操作。', tabsRestoredWithSkipped: '已恢复 {created} 个标签，{failed} 个无法恢复。', restoringTabs: '正在恢复标签',
    deepScanReady: '深度扫描已就绪。', adaptiveMetadataEnabled: '将继续使用智能元数据分析。', permissionDenied: 'Chrome 未授予页面摘要权限。', openingZenTab: '正在打开 Zen Tab', connectingToTabs: '正在连接 Chrome 标签…',
    noMatchingTabs: '没有匹配的标签', clearWindow: '窗口清爽，当前没有打开的标签。', tryShorterTitle: '试试更短的标题或域名。', openTabToAppear: '打开一个标签，它会立即出现在这里。', selected: '已选择', selectionMode: '选择模式 · 点击行来切换', exitSelection: '退出选择模式', moveTabToStart: '移到最前面', moveTabToEnd: '移到最后面', untitledGroup: '未命名分组', ungrouped: '未分组', untitledTab: '未命名标签', selectTab: '选择 {title}', deselectTab: '取消选择 {title}', selectGroup: '选择分组 {name}', selectAll: '全选', closeAll: '全部关闭', clickToSelect: '点击选择或取消选择', actionsFor: '{title} 的操作', playingAudio: '正在播放声音', discarded: '已休眠', discardTab: '休眠此标签', pinned: '已固定', mute: '静音', unmute: '取消静音', pin: '固定', unpin: '取消固定', activate: '激活', close: '关闭', done: '完成', undo: '撤销', dismiss: '关闭提示',
    projectMap: '智能分组建议', suggestedGroups: '{count} 个建议分组', checkTabsEvidence: '创建浏览器分组前，请确认标签与依据。不确定的标签将保留在分组外。', suggestionsToReview: '请检查分组建议', tabsNeedMoreContext: '{count} 个标签需要更多上下文', noValidGroups: '请至少勾选一个包含两个或以上标签的分组。', invalidGroupName: '项目名称需为 1 到 42 个字符。', reviewBeforeApplying: '确认后应用', keepAsIs: '保持不变', createGroups: '创建 {count} 个分组', applying: '正在应用…', lowValueScan: '闲置标签清理', possibleCleanups: '{count} 个建议清理的标签', nothingCloses: '未经勾选确认绝不会关闭任何标签。受保护页面默认展示但不可勾选。', protectedPages: '保守清理机制', conservative: '已自动排除当前活跃、固定、本地页面及受保护域名', leaveEverything: '全部保留', noSafeCleanup: '没有发现适合清理的闲置标签。', contextIntentional: '当前打开的标签均在活跃使用或受保护，无需清理。',
    recoverableContext: '暂存与历史', stashLibraryDescription: '会话均保存在本地，直到你决定删除它们。', stashSearch: '搜索已保存会话', noMatchingStashes: '没有匹配的会话', saved: '已保存', nextFocus: '暂存库为空，随时暂存暂不需要的标签。', restore: '恢复', restoreTab: '恢复标签', restoreGroup: '恢复分组', delete: '删除', renameStash: '重命名暂存', expandStash: '展开暂存', collapseStash: '收起暂存', stashRenamed: '暂存已重命名。', invalidStashName: '暂存名称需为 1 到 80 个字符。', tabsOpening: '正在新窗口打开 {count} 个标签。', stashDeleted: '暂存已删除。', couldNotRestoreStash: '无法恢复暂存。', couldNotDeleteStash: '无法删除暂存。', stashEmptyDescription: '暂存窗口或选中的标签，之后可以随时恢复。', pageNoLongerAvailable: '页面已不可用', keptAside: '有 {count} 个标签暂不分组。它们的项目信号太弱或存在冲突，暂时无法安全判断。',
    controlRoom: '偏好设置', settings: '设置', settingsDescription: '用几个小设置，让自动化始终在你的掌控之中。', language: '语言', languageDescription: '选择 Zen Tab 的界面语言。', theme: '主题', themeDescription: '跟随 Chrome，也可以固定外观。', systemTheme: '系统（跟随 Chrome）', lightTheme: '浅色', darkTheme: '深色', atmosphere: '背景氛围', atmosphereDescription: '侧边栏背景的微弱流动点阵。关闭可获得纯净扁平外观。', duplicateGuard: '重复标签防护', catchRepeated: '重复页面出现时自动提醒。', matchScope: '匹配范围', allNormalWindows: '所有普通窗口', currentWindowOnly: '仅当前窗口', deepScanAll: '深度扫描全部标签', deepScanDescription: '智能分组时深入读取最多 300 个页面的内容摘要。', deepScanPrivacy: '默认关闭。关闭时仅在必要时自适应读取最多 32 个不确定标签的摘要。', aiProvider: 'AI 服务', localAutomatic: '本地 / 自动', savedLocally: '已保存在本地 · 输入新的 Key 可替换', clearApiKey: '清除 API Key', couldNotSaveSettings: '设置保存失败。', protectedDomains: '受保护域名', protectedDomainsDescription: '永远不要为这些域名推荐清理。', protectedDomainsPlaceholder: 'figma.com, docs.google.com', settingsFootnote: 'Zen Tab 依据 Chrome 的休眠状态与安全启发式规则管理标签，不展示估算的单标签内存占用。', strongMatch: '高度匹配', possibleMatch: '可能匹配', needsReview: '需要确认', severalSignals: '多个信号指向同一个项目。', someSignals: '部分信号相似，建议在分组前检查依据。', limitedContext: '上下文不足或存在冲突。', moveTo: '移动到', unclassified: '未分类', renameGroup: '重命名分组', changeGroupColor: '更改分组颜色', ungroup: '取消分组', groupUpdated: '分组已更新。', clearProjectMemory: '清除已学习的分组偏好', clearProjectMemoryDescription: '只有你明确确认过的项目选择会保存在本地，用于改善后续建议。', clearProjectMemoryConfirm: '清除这台设备上的已学习分组偏好？', projectMemoryCleared: '已清除已学习的分组偏好。',     groupColorGrey: '灰色', groupColorBlue: '蓝色', groupColorCyan: '青色', groupColorGreen: '绿色', groupColorYellow: '黄色', groupColorOrange: '橙色', groupColorRed: '红色', groupColorPink: '粉色', groupColorPurple: '紫色',
    ignoredDomains: '忽略域名', ignoredDomainsDescription: '重复标签防护会跳过这些网站。', ignoredDomainsPlaceholder: 'mail.google.com, calendar.google.com', incognitoWindows: '无痕窗口', incognitoWindowsDescription: '允许在无痕窗口中使用去重、分组、清理和暂存。',
    openaiCompatible: 'OpenAI 兼容接口（自带 Key）', openaiBaseUrl: 'API 地址', openaiModel: '模型', openaiApiKey: 'API Key', openaiPrivacy: '保存在本地。只有你选择这个服务后，才会发送标签元数据。Groq、OpenAI 和 Ollama 都可以用同一套接口。', openaiPermissionDenied: '没有获得该 API 地址的网络权限，已继续使用本地模式。', couldNotSaveApiKey: '无法保存 API Key。', apiKeySaved: 'API Key 已保存在本地。', openaiHint: '例如：https://api.groq.com/openai/v1 · https://api.openai.com/v1 · http://127.0.0.1:11434/v1',
    autoDiscard: '自动休眠空闲标签', autoDiscardDescription: '默认关闭。每分钟自动检查空闲标签并释放内存。当前活跃、固定、播放音频、本地和受保护的页面保持常驻。', autoDiscardAfter: '空闲超过', autoDiscardInspect: '跳过有未保存输入的标签', autoDiscardInspectDescription: '检查未保存的表单内容、在线编辑器及正在播放的媒体。需页面访问权限；未授权时将保持标签唤醒。', minutes15: '15 分钟', minutes30: '30 分钟', minutes60: '1 小时', minutes120: '2 小时',
    commandPalette: '命令面板', commandPalettePlaceholder: '输入命令、标签、暂存或书签', cmdStashWindow: '暂存当前窗口', cmdStashAll: '暂存窗口中的全部标签', cmdGroup: '智能分组', cmdCleanup: '清理低频标签', cmdSettings: '打开设置', cmdFocusSearch: '聚焦搜索框', cmdStashLibrary: '打开暂存库', cmdBookmarks: '打开书签', cmdUndo: '撤销上一步', cmdExportWindow: '导出当前窗口为 JSON', cmdJumpTab: '切换到标签', cmdJumpStash: '打开暂存', cmdJumpBookmark: '打开书签', cmdSwitchWindow: '切换窗口', noMatchingCommands: '没有匹配的命令、标签或书签。',
    paletteBadgeActive: '当前', paletteBadgeTab: '标签', paletteBadgeBookmark: '书签', paletteBadgeStash: '暂存', paletteBadgeWindow: '窗口', paletteBadgeCommand: '指令', activeTab: '当前标签',
    settingsAppearance: '外观', settingsTabs: '标签', settingsAi: 'AI', settingsPrivacy: '隐私', collapseFolder: '折叠文件夹', expandFolder: '展开文件夹', dropToFile: '拖到这里收藏', emptyFolderDropHint: '空文件夹 · 拖到此处', bookmarksCreated: '已保存 {count} 个书签。',
    exportJson: '导出 JSON', exportMarkdown: '导出 Markdown', exportWindow: '导出窗口', importFile: '导入 JSON', importOneTab: '导入 OneTab 文本', importedStashes: '已导入 {count} 个会话到暂存库。', couldNotImport: '无法导入这个文件。', noImportEntries: '这段文本里没有找到网址。', oneTabImportName: 'OneTab 导入', windowExportName: '窗口 {index}', importJsonTooltip: '从导出的 Zen Tab JSON 文件恢复会话', importOneTabTooltip: '导入 OneTab 插件格式的网址列表（每行 网址 | 标题）',
    recentlyClosed: '最近关闭', restoreClosed: '恢复', closedWindow: '已关闭窗口', closedTab: '已关闭标签', couldNotListSessions: '无法读取最近关闭的会话。', showAllRecent: '展开全部 {count} 项', showLessRecent: '收起',
    playingNow: '正在播放', muteAllAudio: '全部静音', jumpToAudio: '跳到发声标签', cancel: '取消',
    couldNotLoadBookmarks: '无法加载书签。', bookmarkSearchResults: '搜索结果', bookmarkInbox: '未归类收件箱', bookmarksFiled: '已将 {count} 个书签归档到 {folder}。', noDuplicateBookmarks: '没有发现重复书签。', duplicateBookmarksRemoved: '已移除 {count} 个重复书签。', bookmarkSummaryUnavailable: '无法为这个书签读取页面摘要。', bookmarkSummarySaved: '页面摘要已保存，可用于书签搜索。', loadingBookmarks: '正在加载书签…', bookmarkPermissionTitle: '连接你的书签', bookmarkPermissionBody: 'Zen Tab 需要书签权限来搜索和归档已保存页面。', grantBookmarkAccess: '授予书签权限', bookmarkLibraryDescription: '{count} 个已保存页面', findDuplicates: '查找重复项', bookmarkSuggestedFolder: '建议文件夹：{folder}', bookmarkChooseFolder: '选择这个新书签的归档位置。', review: '查看', noMatchingBookmarks: '没有匹配的书签', noBookmarksYet: '还没有书签', tryDifferentBookmarkSearch: '试试标题、域名、文件夹或已保存的页面摘要。', saveBookmarkToAppear: '在 Chrome 中保存页面后，它会显示在这里。', enrichBookmark: '添加打开页面的内容用于搜索', openBookmark: '打开', fileBookmark: '归档', chooseBookmarkFolder: '选择文件夹', noBookmarkFolders: '请先创建书签文件夹', bookmarkDedupTitle: '检查重复书签', bookmarkDedupEyebrow: '书签清理', bookmarkDedupDescription: '仅保留勾选的副本，确认后才会删除重复项。', bookmarkDedupKeep: '保留在 {folder}', bookmarkDedupRemove: '移除 {count} 个额外副本', removeDuplicateBookmarks: '移除 {count} 个重复项',
    editBookmark: '编辑', deleteBookmark: '删除', newBookmarkFolder: '新建文件夹', renameBookmarkFolder: '重命名', deleteBookmarkFolder: '删除文件夹', openAllBookmarks: '全部打开',
    bookmarkChipAll: '全部', bookmarkChipInbox: '收件箱', bookmarkChipDuplicates: '重复', bookmarkTitleLabel: '名称', bookmarkUrlLabel: '网址', saveBookmarkEdit: '保存',
    invalidBookmarkUrl: '请输入有效的网址。', deleteFolderConfirm: '删除这个文件夹及其全部内容？', openAllBookmarksConfirm: '打开 {count} 个书签？', bookmarkFolderName: '文件夹名称', bookmarksSkipped: '已跳过 {count} 条。',
    reviewInbox: '审查未分类书签', skipBookmark: '跳过', newFolderInReview: '新建文件夹', newFolderParent: '上级文件夹', bookmarkInboxHint: '还没放进文件夹。',
    bookmarkOrganize: '整理', unfiledBookmarkCount: '{count} 个未归类', reviewUnfiled: '审查未分类书签', bookmarkMoved: '书签已移动。', bookmarkOrganizeDescription: '智能聚类整理书签并识别重复项。确认后才会应用改动。', fileSuggestedBookmarks: '归档 {count} 条建议', noFilingSuggestions: '还没有文件夹建议。可以手动审查未分类书签。', organizeInboxTitle: '收件箱归档',
    organizeClustersTitle: '建议文件夹', organizeCreateFolder: '新建文件夹', organizeExistingFolder: '已有文件夹', organizeClusterCount: '{count} 个书签', applyOrganizePlan: '应用 {count} 项整理', noOrganizeSuggestions: '暂无建议分组。需存在相同网站或关键词的书签，或已有匹配的目标文件夹。', bookmarksOrganized: '已整理 {count} 个书签。', organizeMoreBookmarks: '还有 {count} 个',
    organizeByTopic: '按主题整理', organizeAnalyzing: '正在按主题分组…', organizeNeedsModel: '按主题整理需要 Chrome 内置端侧模型或在设置中配置 API Key。', organizeAnalyzedCount: '已分析 {analyzed} / {eligible} 个书签', organizeShowHostClusters: '只看按网站分组', organizeTopicFailed: 'AI 主题分析未成功，已自动降级为网站启发式分组。',
    organizeSnapshotsTitle: '历史还原点', organizeSnapshotMeta: '{count} 个书签 · 剩余 {days} 天', organizeRestore: '还原', organizeRestoreConfirm: '将这些书签恢复到 {time} 的整理前位置？之后手动移动过的书签也会一并复原。', organizeRestored: '已还原 {count} 个书签。', organizeSnapshotSaveFailed: '已整理，但 7 天还原点保存失败。', organizeNothingToApply: '没有可应用的改动。',
    organizeScopeUnfiled: '未归类（推荐）', organizeScopeBar: '书签栏', organizeScopeOther: '其他书签', organizeScopeAll: '全部书签', organizeScopeLabel: '整理范围', organizeTargetFolder: '目标文件夹', organizeNewFolderLabel: '新建：{name}', organizeIncludedCount: '应用选中的 {count} 项整理', organizeCandidateCount: '{count} 个待整理书签', organizeShowLess: '收起',
    exportBookmarks: '导出', exportAddsNotReplaces: '导入这份 HTML 会新增一棵文件夹树，不会替换现有书签。', exportNetscapeHtml: '导出 HTML', downloadExport: '下载',
    builtInAi: '端侧模型', builtInAiUnsupported: '当前 Chrome 不支持。', builtInAiUnavailable: '这台设备不可用。', builtInAiDownloadable: '分组需要时可以下载。', builtInAiDownloading: '正在下载端侧模型…', builtInAiAvailable: '可离线用于分组。', builtInAiDownload: '下载端侧模型', builtInAiDownloadProgress: '正在下载端侧模型… {percent}%',
  },
};

export function createTranslator(language: Language): Translator {
  const dictionary = translations[language] ?? translations.en;
  const isMac = typeof navigator !== 'undefined' && /(Mac|iPhone|iPod|iPad)/i.test(navigator.platform || navigator.userAgent);
  const defaultValues: Record<string, string> = {
    shortcut: isMac ? '⌘K' : 'Ctrl+K',
  };
  return (key, values = {}) => {
    const template = dictionary[key] ?? translations.en[key] ?? key;
    const merged = { ...defaultValues, ...values };
    return template.replace(/\{(\w+)\}/g, (_, name: string) => String(merged[name] ?? `{${name}}`));
  };
}
